ny_taxi_analytics:
  outputs:
    dev:
      dataset: "{{ env_var('GCP_BQ_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: "{{ env_var('GCP_BQ_LOCATION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_BQ_PROJECT') }}"
      threads: 4
      type: bigquery
  target: dev
