version: '3'
services:
  dbt-bq:
    build:
      context: .
      target: dbt-bigquery
    image: dbt/bigquery
    env_file:
      - dev.env
    environment:
      - DBT_PROFILES_DIR=/root/.dbt/
      - DBT_LOG_PATH=/usr/app/logs/
    volumes:
      - ./dbt-docker/ny_taxi_analytics/:/usr/app/
      - ./.dbt/:/root/.dbt/
      - ./.credentials/dtc-de-course-410021-60ea3845a080.json:/.google/credentials/google_credentials.json
    network_mode: host